# 1️⃣ Utiliser une image Python avec Scrapy
FROM python:3.9

# 2️⃣ Définir le dossier de travail dans le conteneur
WORKDIR /netflix_scraper

# 3️⃣ Copier les fichiers du projet dans l'image Docker
COPY . .

# 4️⃣ Installer Scrapy et les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# 5️⃣ Attendre que MongoDB soit prêt avant d'exécuter Scrapy
CMD ["sh", "-c", "./wait-for-it.sh mongodb:27017 -- scrapy crawl netflix_top10"]
